---
- name: install nfs-utils
  yum:
    name: nfs-utils
    state: latest

- name: start and enable nfs server service
  service:
    name: nfs-server
    state: started
    enabled: yes

- name: export directory
  lineinfile:
    path: /etc/exports
    line: "{{ nfsPath }} *(rw,sync,no_root_squash)"
  register: export_result

- name: create directory
  file:
    path: "{{ nfsPath }}"
    state: directory
    group: nobody
    owner: nobody
    mode: "0777"

- name: execute export
  command: sudo exportfs -arv
  when: export_result.changed
