---
- name: Install dependencies
  ansible.builtin.dnf:
    name: 
      - postfix
    state: latest
- name: postfix service enabled
  ansible.builtin.service:
    name: postfix
    enabled: yes
    state: started
