---
- name: Install dependencies
  ansible.builtin.dnf:
    name: 
      - curl
      - policycoreutils
      - openssh-server
      - perl
    state: latest
 - name: ssh service enabled
   ansible.builtin.service:
     name: sshd
     enabled: yes
 - name: ssh service start
   ansible.builtin.service:
     name: sshd
     state: started
 18 ... 
