- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Install Docker CE
  yum:
    name: docker-ce
    state: present
    update_cache: yes

- name: Make sure docker service is running
  systemd:
    state: started
    name: docker

- name: enable service docker and ensure it is not masked
  systemd:
    name: docker.service
    enabled: yes
    masked: no
  notify: alternative-python

