- name: install pkg for docker
  dnf:
    name:
      - epel-release
      - git
      - gcc
      - gcc-c++
      - nodejs
      - gettext
      - device-mapper-persistent-data
      - lvm2
      - bzip2
      - python3-pip
    state: latest

- name: install ansible
  dnf:
    name:
      - ansible
    state: latest

- name: install containered.io rpm from a remote repo
  yum:
    name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    state: present

