---
- name: add ansible user and place ssh public key
  hosts: rootkvm
  roles:
  - user-add

- name: set hostname
  hosts: kvm
  become: yes
  roles: 
  - hostname-set

- name: place network scripts
  hosts: kvm
  become: yes
  roles: 
  - network
