---
- name: add ansible user, set ssh config and place ssh public key
  hosts: roottotal
  roles:
  - user-add
  - ssh-configure

- name: set correct timezone 
  hosts: roottotal
  roles:
  - time-set

- name: place network scripts
  hosts: roottotal
  roles: 
  - network
