---
- name: add ansible user and place ssh public key
  hosts: rootcloud1
  roles:
  - user-add

- name: set hostname
  hosts: cloud1
  become: yes
  roles: 
  - hostname-set

- name: place network scripts
  hosts: cloud1
  become: yes
  roles: 
  - network
