---
- name: add ansible user and place ssh public key
  hosts: rootall
  roles:
  - user-add

- name: set hostname
  hosts: all
  become: yes
  roles: 
  - hostname-set

- name: place network scripts
  hosts: all
  become: yes
  roles: 
  - network

- name: update yum packages
  hosts: all
  become: yes
  roles:
  - yum-update

- name: install and enable kvm
  hosts: all
  become: yes
  roles:
  - libvirt-install
  tags:
  - kvm

- name: install KVM and all of its dependencies
  hosts: all
  become: yes
  roles: cockpit-install
  tags:
  - kvm
  - nfs

- name: provide nfs storage
  hosts: all
  become: yes
  roles:
  - nfs-provide
  tags:
  - nfs

- name: shut down host
  hosts: all
  become: yes
  roles:
  - shutdown
