---
- name: add ansible user and place ssh public key
  hosts: localhost #roottotal
  become: yes
  roles:
  - user-add

- name: place network scripts
  hosts: localhost #roottotal
  become: yes
  roles: 
  - network
