---
- name: add ansible user and place ssh public key
  hosts: rootvm
  roles:
  - user-add

- name: set hostname
  hosts: vm
  become: yes
  roles: 
    - hostname-set

- name: place network scripts
  hosts: vm
  become: yes
  roles: 
    - network
