---
- name: update yum packaged
  hosts: kvm
  become: yes
  roles:
  - yum-update

- name: install and enable kvm, cockpit and all its dependencies
  hosts: kvm
  become: yes
  roles:
  - libvirt-install
  - cockpit-install

- name: provide nfs storage
  hosts: kvm 
  become: yes
  roles:
  - nfs-provide

- name: shut down host
  hosts: kvm
  become: yes
  roles:
  - shutdown
