---
- name: update yum packaged
  hosts: dev
  become: yes
  roles:
  - yum-update

- name: install and enable kvm, cockpit and all its dependencies
  hosts: dev
  become: yes
  roles:
  - libvirt-install
  - cockpit-install
