---
- name: update yum packaged
  hosts: kvm
  become: yes
  roles:
  - yum-update

- name: install and enable cockpit and all its dependencies
  hosts: kvm
  become: yes
  roles:
  - cockpit-install
