---
- name: set hostname like ansible inventory name
  hosts: total
  become: yes
  roles:
  - hostname-set

- name: update yum packages
  hosts: total
  become: yes
  roles:
  - yum-update

- name: install and enable kvm
  hosts: total
  become: yes
  roles:
  - libvirt-install
  tags:
  - kvm

- name: install cockpit and all of its dependencies
  hosts: nfs
  become: yes
  roles: 
  - cockpit-install
  tags:
  - kvm
  - nfs

- name: provide nfs storage
  hosts: nfs
  become: yes
  roles:
  - nfs-provide
  tags:
  - nfs

- name: install anydesk
  hosts: total
  become: yes
  roles:
  - anydesk-install
  tags:
  - desktop

- name: create software mirror
  hosts: ansibleMaster
  become: yes
  roles: 
  - repo-provide

- name: add mirror
  hosts: total
  become: yes
  roles:
  - mirror-add
  - yum-update
