---
- name: set hostname like ansible inventory name
  hosts: total
  become: yes
  roles:
  - hostname-set

- name: update yum packages
  hosts: total
  become: yes
  roles:
  - yum-update

- name: install and enable kvm
  hosts: kvm
  become: yes
  roles:
  - libvirt-install

- name: install cockpit and all of its dependencies
  hosts: nfs
  become: yes
  roles: 
  - cockpit-install

- name: create CA certificate on every host
  hosts: total
  become: yes
  roles:
  - certificate-create

- name: provide nfs storage
  hosts: nfs
  become: yes
  roles:
  - nfs-provide

- name: install anydesk
  hosts: nfs
  become: yes
  roles:
  - anydesk-install

- name: create software mirror
  hosts: dev7
  become: yes
  roles: 
  - repo-provide

- name: add mirror
  hosts: total
  become: yes
  roles:
  - mirror-add

- name: update mirror list and yum repo
  hosts: total
  become: yes
  roles:
  - yum-update
