---
- name: add local mirror to .repo 
  yum_repository:
    name: local
    description: local mirror for faster install
    baseurl: "https://{{ ansibleMaster }}/"
    gpgcheck: no
    enabled: yes
