---
- name: include provide-storage-vars
  include_vars: provide-storage-vars.yml

- name: list all VMs
  virt:
    command: list_vms
  register: all_vms

- name: debug - show all running vms on slaves
  debug: 
    msg: "{{ all_vms }}"

- block:
  - name: install epel-release package
    dnf:
      name: epel-release
      state: latest
        
  - name: enable powertools
    ini_file:
      path: /etc/yum.repos.d/CentOS-PowerTools.repo
      section: PowerTools
      option: enabled
      value: "1"
    notify:
      - yum update cache
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version >= "8"

  - name: install R package
    yum:
      name: R
      state: latest

  - name: make safe copy from golden image
    command: "cp {{ goldendir }}cent-8-gold.qcow2 {{ livedir }}{{ vmname }}.qcow2"
        
  - name: create new virtual machine
    command: >
             virt-install 
             --network default
             --name "{{ vmname }}"
             --os-variant=centos8
             --ram="{{ vram }}"
             --vcpus="{{ vcpu }}"
             --import
             --disk "{{ livedir }}{{ vmname }}.qcow2"
             --autostart
             --graphics vnc
             --noautoconsole
    async: 10
    poll: 0  
    register: result
    notify: counter

  - name: show output of vm creation script
    debug:
      msg: "{{ result }}"

  when: '"{{ vmname }}" not in all_vms.list_vms'

- name: push git
  command: bash /home/master/ansible-kvm/scripts/sh/adall.sh
  become_user: master
  args:
    chdir: /home/master/ansible-kvm
