---
- name: make shure directory for cockpit config file exists
  file:
    state: directory
    path: /etc/cockpit

- name: place config file for cockpit, disabling timout
  template:
    src: cockpit.conf
    dest: /etc/cockpit/cockpit.conf

- name: install yum modules
  yum:
    name: 
      - epel-release
      - wget
      - htop
      - vim
    state: latest

- name: install the latest version of cockpit and additional modules
  dnf:
    name:
      - cockpit
      - cockpit-machines
      - cockpit-dashboard
      - cockpit-podman 
      - cockpit-networkmanager 
      - cockpit-packagekit 
      - cockpit-storaged
    state: latest

- name: Start service cockpit, if not started
  service:
    name: cockpit.socket
    state: started

- name: enable service cockpit and ensure it is not masked
  systemd:
    name: cockpit.socket
    enabled: yes
    masked: no

- name: add cockpit to firewalld, restart if changed
  firewalld:
    service: cockpit
    permanent: yes
    state: enabled
  notify: firewalld restart
