---
- name: download certificate from master server
  copy:
    src: /etc/pki/tls/certs/localhost.crt
    dest: /etc/pki/ca-trust/source/anchors/
  register: certCopy

- name: reload CA certificates
  command: update-ca-trust
  when: certCopy.changed
