---
- name: scriptfolder
  file:
    path: "/etc/sysconfig/network-scripts/"
    state: directory

- name: devscript
  template:
    src: ifcfg-Wired_connection_1
    dest: /etc/sysconfig/network-scripts
    owner: root
    group: root
    mode: '0644'

- name: bridgescript
  template:
    src: ifcfg-bridge0
    dest: /etc/sysconfig/network-scripts
    owner: root
    group: root
    mode: '0644'

- name: nmrestart
  service:
    name: NetworkManager
    state: restarted

