---
- name: make shure directory for cockpit config file exists
  file:
    state: directory
    path: /etc/modprobe.d

- name: place config file for cockpit, disabling timout
  template:
    src: kvm.conf
    dest: /etc/modprobe.d/kvm.conf

- name: install the latest version of virt
  dnf:
    name:
      - virt-install
      - virt-viewer
    state: latest

- name: install the latest libguestfs-tools
  yum:
    name:
      - libguestfs-tools
    state: latest

- name: Start service libvirtd, if not started
  service:
    name: libvirtd
    state: started

- name: enable service libvirtd.service and ensure it is not masked
  systemd:
    name: libvirtd
    enabled: yes
    masked: no
