---
- name: install the latest version of virt
  dnf:
    name:
      - virt-install
      - virt-viewer
    state: latest

- name: install the latest libguestfs-tools
  yum:
    name:
      - libguestfs-tools
    state: latest

- name: Start service libvirtd, if not started
  service:
    name: libvirtd
    state: started

- name: enable service libvirtd.service and ensure it is not masked
  systemd:
    name: libvirtd
    enabled: yes
    masked: no
