---
- name: install dependencies for shared storage 
  dnf:
    name: nfs-utils
    state: latest

- name: create shared-storage folder
  file:
    path: "{{ shareddir }}"
    state: directory
    owner: nobody
    mode: 0755

- name: enable service nfs and ensure it is not masked
  systemd:
    name: nfs-server.service
    enabled: yes
    masked: no

- name: Create a ext4 filesystem on /dev/sdb
  filesystem:
    fstype: ext4
    dev: /dev/sdb

- name: Mount up device by name
  mount:
    path: "{{ shareddir }}"
    src: /dev/sdb
    fstype: ext4
    opts: noatime
    state: mounted

- lineinfile:
    path: /etc/exports
    line: "{{ shareddir }} *(rw,sync,no_all_squash,root_squash)"
    create: yes
  notify:
    - exportfsa
    - restart-nfs

- name: create folder structure on shared-storage
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: nobody
  with_items:
  - ["{{ goldendir }}","{{ isodir }}","{{ snapdir }}","{{ livedir }}"]

- name: Configure firewall rules for NFS server
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: ["nfs","mountd","rpc-bind"]
