---
- name: include vars from provide storage role
  include_vars: /home/master/ansible-kvm/roles/provide-storage/vars/main.yml

- name: include vars from clone-centos role
  include_vars: /home/master/ansible-kvm/roles/clone-centos/vars/main.yml

- name: make safe copy from golden image
  command: "cp {{ goldendir }}cent-8-gold.qcow2 {{ livedir }}{{ vmname }}.qcow2"
        
- name: create new virtual machine
  command: >
           virt-install 
           --network default
           --name "{{ vmname }}"
           --os-variant="{{ osvar }}" 
           --ram="{{ vram }}"
           --vcpus="{{ vcpu }}"
           --import
           --disk "{{ livedir }}{{ vmname }}.qcow2"
           --autostart
           --graphics vnc
           --noautoconsole
  async: 10
  poll: 0  
