---
- name: Create the network configuration file for ethernet interfaces
  template:
    src: "ethernet_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_ether_interfaces }}"
  notify: network-restart
  when: 
    - network_ether_interfaces is defined
  register: ether_result

- name: Create the network configuration file for bridge devices
  template:
    src: "bridge_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_bridge_interfaces }}"
  notify: network-restart
  when: network_bridge_interfaces is defined
  register: bridge_result

- name: Enable the "NetworkManager" service
  service:
    name: NetworkManager
    enabled: true
  failed_when: false
