---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Create the network configuration file for ethernet interfaces
  template:
    src: "ethernet_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_ether_interfaces }}"
  when: 
    - network_ether_interfaces is defined
    - network_bond_interfaces is not defined
  register: ether_result

- name: Create the network configuration file for vlan devices
  template:
    src: "ethernet_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_vlan_interfaces }}"
  when: network_vlan_interfaces
  register: vlan_result

- name: Create the network configuration file for bridge devices
  template:
    src: "bridge_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_bridge_interfaces }}"
  when: network_bridge_interfaces is defined
  register: bridge_result

- name: reboot machine if network changed
  reboot:
  ignore_errors: 'yes'
  when: vlan_result.changed or bridge_result.changed or ether_result.changed
