---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include specific tasks for the RedHat family
  include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Create the network configuration file for ethernet interfaces
  template:
    src: "ethernet_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_ether_interfaces }}"
  when: 
    - network_ether_interfaces is defined
    - network_bond_interfaces is not defined
  register: ether_result
  tags: 
    - route

- name: Create the network configuration file for slave in the bond devices
  template:
    src: "bond_slave_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.1 }}"
  with_subelements:
    - "{{ network_bond_interfaces }}"
    - bond_slaves
  when: network_bond_interfaces is defined
  register: bond_port_result

- name: Create the network configuration file for bond devices
  template:
    src: "bond_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_bond_interfaces }}"
  when: network_bond_interfaces is defined
  register: bond_result

- name: Make sure the bonding module is loaded
  modprobe:
    name: bonding
    state: present
  when: bond_result is changed

- name: create modules file if not exists
  copy: 
    content: "" 
    dest: /etc/modules-load.d/bonding
    force: no
  when: network_bond_interfaces is defined

- name: Make the bonding module persistent
  become: true
  lineinfile:
    line: 'bonding'
    dest: /etc/modules-load.d/bonding
    insertafter: EOF
  when:
    - network_bond_interfaces is defined
    - network_modprobe_persist

- name: Create the network configuration file for vlan devices
  template:
    src: "ethernet_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_vlan_interfaces }}"
  when: network_vlan_interfaces
  register: vlan_result

- name: Make sure the 8021q module is loaded
  modprobe:
    name: 8021q
    state: present
  when: vlan_result is changed

- name: Make the 8021q module persistent
  become: true
  lineinfile:
    line: '8021q'
    dest: /etc/modules
    insertafter: EOF
  when:
    - network_vlan_interfaces
    - network_modprobe_persist

- name: Create the network configuration file for bridge devices
  template:
    src: "bridge_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_bridge_interfaces }}"
  when: network_bridge_interfaces is defined
  register: bridge_result

- name: Create the network configuration file for port on the bridge devices
  template:
    src: "bridge_port_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.1 }}"
    with_subelements:
      - '{{ network_bridge_interfaces }}'
      - bridge_ports
  when: bridge_ports is defined
  register: bridge_port_result

- include: restartscript.yml
  when: bridge_result.changed or bond_result.changed or ether_result.changed
