---
# Restart interfaces to load new configuration
#
# We had a lot of problems with lost connectivity, therefore we changed the
# role to use a script for network reconfiguration.
# Tested on Debian Jessie / Ubuntu 14.04 LTS and with Ethernet, Bonding Interfaces

- name: Create a restart script
  template:
    src: restartscript.j2
    dest: /etc/sysconfig/restart.sh
    mode: 0755

# Execute configuration change
- name: Execute Network Restart
  shell: bash /etc/sysconfig/restart.sh | true
  ignore_errors: 'yes'
