---
- name: Create a restart script
  template:
    src: restartscript.j2
    dest: /tmp/restart.sh
    mode: 0755

- name: Execute Network Restart
  shell: /tmp/restart.sh | true
  ignore_errors: 'yes'
