---
- name: find all certificate files from master server
  find:
    path: /tmp/
    patterns: "*.*rt"
  register: findCert
  delegate_to: localhost

- name: download certificate from master server
  copy:
    src: "{{ item.path }}"
    dest: /etc/pki/ca-trust/source/anchors/
  loop: "{{ findCert.files }}"
  loop_control:
    label: "{{ item.path }}"
  notify: caReload
