---
- name: install epel-release
  yum:
    name: epel-release
    state: latest

- name: install required packages and common packages
  yum:
    name:
    - yum-utils
    - htop
    - wget
    - vim
    - git
    - open-vm-tools
    - python3
    - python3-pip
    state: latest
  failed_when: no
