---
- name: install epel-release
  yum:
    name: epel-release
    state: latest

- name: install required packages and common packages
  yum:
    name:
    - yum-utils
    - htop
    - wget
    - vim
    - python3
  state: latest
