---
- name: install epel-release
  yum:
    name: epel-release
    state: latest

- name: install required packages and common packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
  - yum-utils
  - htop
  - wget
  - vim
