---
- name: register if container is already running
  shell: docker ps -a
  register: runningContainers 

- name: start build and push container, start and enable
  shell: bash adnpush.sh; bash runner.sh
  become_user: "{{ user }}"
  args:
    chdir: "{{ repoDirectory }}"
  when: not containerName in runningContainers.stdout_lines
