---
- name: place httpd config file
  template:
    dest: "/etc/httpd/conf/httpd.conf"
    src: httpd.conf.j2
  notify: httpdRestart

- name: place sites available
  template:
    dest: "/etc/httpd/sites-available/{{ ansibleMaster }}.conf"
    src: domain.conf.j2

- name: create simlink from available to enabled
  file:
    src: "/etc/httpd/sites-available/{{ ansibleMaster }}.conf"
    dest: "/etc/httpd/sites-enabled/{{ ansibleMaster }}.conf"
    state: link
  notify: httpdRestart
