---
- name: place httpd config file
  template:
    dest: "/etc/httpd/conf/httpd.conf"
    src: httpd.conf.j2
  notify: httpdRestart

- name: remove apache welcome page
  file:
    dest: "{{ httpdDir }}conf.d/welcome.conf"
    state: absent
