---
- include_tasks: packages-install.yml
- include_tasks: files-folders.yml
- include_tasks: basic-auth.yml
- include_tasks: httpd-set.yml
- include_tasks: firewall-set.yml
- include_tasks: certificate-publish.yml
 
