---
- name: place cronjobs
  cron:
    name: "{{ item.name }}"
    weekday: "1-5"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    user: ansible
    job: "{{ item.job }}"
    cron_file: "{{ item.name }}"
  loop:
  - name: "mariadbBackup"
    minute: "00"
    hour: "03"
    job: "$(bash {{ backupPath }}/mariadbBackupScript) 2>> /var/log/mariadbBackup.log"
  - name: "mariadbBackupLogSave"
    minute: "04"
    hour: "00"
    job: "cp /var/log/mariadbBackup.log {{ backupPath }} -f"
