---
- name: create directories required for this role
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
  - "{{ certDirectory }}"
  - "{{ repoDirectory }}centosplus/"
  - "{{ repoDirectory }}base/"
  - "{{ repoDirectory }}extras/"
  - "{{ repoDirectory }}updates/"
  - "{{ httpdDirectory }}sites-available/"
  - "{{ httpdDirectory }}sites-enabled/"
  notify: 
  - reposync
