---
- name: create directory for the repositories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
  - /localrepo/

- name: unpack rpm files to directory localrepo
  unarchive:
    copy: yes
    src: "{{ item }}"
    dest: /localrepo
  with_fileglob: /var/packages/*.tar.gz
  register: unpackResult 

- name: copy rpm files to directory localrepo
  copy:
    src: "{{ item }}"
    dest: /localrepo
  with_fileglob: /var/packages/*.rpm
  register: copyResult

- name: copy license folder to directory
  copy:
    src: "{{ item }}"
    dest: /localrepo/licenses/
  loop:
  - /var/licenses/
