---
- name: create directory for the repositories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
  - /localrepo/

- name: unpack rpm files to directory
  unarchive:
    copy: yes
    src: "{{ item }}"*.tar.gz
    dest: /localrepo
  loop: 
  - /var/packages/
  register: copyResult 

- name: copy license folder to directory
  copy:
    src: "{{ item }}"
    dest: /localrepo/licenses/
  loop:
  - /var/licenses/
