---
- name: create directories required for this role
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
  - /etc/pki/tls/certs
  - /etc/pki/tls/private
  - /localrepo/certificates

- name: unpack rpm files to directory localrepo
  unarchive:
    copy: yes
    src: "{{ item }}"
    dest: /localrepo
  with_fileglob: /var/packages/*.tar.gz
  register: unpackResult 

- name: copy rpm files to directory localrepo
  copy:
    src: "{{ item }}"
    dest: /localrepo
  with_fileglob: /var/packages/*.rpm
  register: copyResult

- name: copy files folder to directory
  copy:
    src: "{{ item }}"
    dest: /localrepo/files/
  loop:
  - /var/files/
