---
- name: create directories required for this role
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
  loop:
  - "{{ certDir }}"
  - "{{ repoDir }}centosplus/"
  - "{{ repoDir }}base/"
  - "{{ repoDir }}extras/"
  - "{{ repoDir }}updates/"
  - "{{ httpdDir }}sites-available/"
  - "{{ httpdDir }}sites-enabled/"
  register: dirResult

- name: reposync
  shell: "reposync -g -l -d -m --repoid=centosplus --newest-only --download-metadata --download_path=/var/www/html/repos/"
  when: dirResult.changed
  notify: createrepo
