---
- name: create directory for the repositories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
  - /localrepo/

- name: find all .tar.gz files to be unpacked
  find:
    paths: /localrepo/
    patterns: '*.tar.gz'
  register: gzFiles

- name: unpack rpm files to directory
  unarchive:
    copy: yes
    src: "/localrepo/"
    dest: /localrepo
  loop: 
  - /var/packages/
  register: copyResult 

- name: copy license folder to directory
  copy:
    src: "{{ item }}"
    dest: /localrepo/licenses/
  loop:
  - /var/licenses/
