---
- name: create directory for the repositories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
  - /localrepo/licenses

- name: copy rpm files to directory
  copy:
    src: "{{ item }}"
    dest: /localrepo
  loop: 
  - /var/packages/

- name: copy license files to directory
  copy:
    src: "{{ item }}"
    dest: /localrepo/licenses
  loop:
  - /var/licenses
