---
- name: place page config file file
  template:
    dest: "{{ httpdDir }}sites-available/{{ ansibleMaster }}.conf"
    src: httpd.conf

- name: create symlink
  file:
    state: link
    src: "{{ httpdDir }}sites-available/{{ ansibleMaster }}.conf"
    dest: "{{ httpdDir }}sites-enabled/{{ ansibleMaster }}.conf"
  notify:
  - httpdRestart
  - httpsFirewalld

- name: remove apache welcome page
  file:
    dest: "{{ httpdDir }}conf.d/welcome.conf"
    state: absent
  notify: 
  - httpdRestart
  - httpsFirewalld
