---
- name: place httpd config file
  template:
    dest: /etc/httpd/conf/httpd.conf
    src: httpd.conf
  register: templateresult

- name: remove apache welcome page
  file:
    dest: /etc/httpd/conf.d/welcome.conf
    state: absent

- name: restart service if httpd tempalte changed
  service:
    name: httpd
    state: restarted
    enabled: yes
  when: templateresult.changed
