---
- name: set standard password for anydesk
  command: "echo mypassword | anydesk --set-password"
  when: install_result.changed

- name: check if gdm3 is used
  stat:
    path: /etc/gdm3
  register: file_details

- name: disable wayland
  lineinfile:
    dest: /etc/gdm3/custom.conf
    line: "WaylandEnable=false"
    state: present
  when: file_details.stat.exists
