---
- name: Send a magic Wake-on-LAN packet to all 3 slaves
  wakeonlan:
    mac: "{{ item }}"
  loop: 
    - "{{ slave1_mac_adress }}"
    - "{{ slave2_mac_adress }}"
    - "{{ slave3_mac_adress }}"

- name: wait for slaves to finish boot
  wait_for:
    port: "{{ 22 }}"
    host: "{{ item }}"
    search_regex: OpenSSH
    delay: 1  # Do not check for at least 1 sec
  with_items:
    - "{{  hostvars[groups['slaves'][0]].inventory_hostname }}"
    - "{{  hostvars[groups['slaves'][1]].inventory_hostname }}"
    - "{{  hostvars[groups['slaves'][2]].inventory_hostname }}"
