---
- name: create private ssl key
  openssl_privatekey:
    path: "{{ privateDir }}{{ inventory_hostname }}.key"

- name: create csr
  openssl_csr:
    path: "{{ certDir }}{{ inventory_hostname }}.csr"
    privatekey_path: "{{ privateDir }}{{ inventory_hostname }}.key"
    subject: DE
    ST: NRW
    L: Duesseldorf
    O: VCC
    OU: 
    - Engeneering
    - Automation Service
    CN: "{{ hostvars[inventory_hostname].ansible_host }}"

- name: create self-signed certificate from csr
  openssl_certificate:
    path: "{{ certDir }}{{ inventory_hostname }}.crt"
    privatekey_path: "{{ privateDir }}{{ inventory_hostname }}.key"
    csr_path: "{{ certDir }}{{ inventory_hostname }}.csr" 
    provider: selfsigned

- name: copy certificate to tmp
  copy:
    src: "{{ certDir }}{{ inventory_hostname }}.crt"
    dest: /tmp/
    flat: yes
