---
- name: create directories required for this role
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    recurse: no
    mode: "{{ item.mode }}"
  loop:
  - { path: "{{ privateDir }}", mode: "700" }
  - { path: "{{ certDir }}", mode: "710" }
